---
title: "Linear Models"
author: "Nidhi Patel"
date: "12/8/2020"
output: github_document
---
```{r}
library(tidyverse)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.height = 6,
  out.width = "90%")

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Import data

```{r}
data("nyc_airbnb")

airbnb = nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    boro = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)
```

## Fit a model
We want a line per each borough. 
```{r}
airbnb %>% 
  ggplot(aes(x = stars, y = price, color = boro)) +
  geom_point()
```

Let's fit the model we care about. relating price to starts and boro

```{r}
fit = lm(price ~ stars + boro, data = airbnb)
```

Look at the result

```{r, include = FALSE}
fit

summary(fit)
summary(fit)$coef
coef(fit)
fitted.values(fit)
residuals(fit)
```

Let's look at the results better

```{r}
broom::glance(fit)
#this produces a tibble, rather than a matrix like the code chunk above

broom::tidy(fit) %>% 
  select(-std.error, -statistic) %>% 
  mutate(
    term = str_replace(term, "borough", "Boro: ")
  )

```

