---
title: "Live class"
author: "Nidhi Patel"
date: "11/24/2020"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.height = 6,
  out.width = "90%")

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Read in data


```{r}
homicide = read_csv("./data/homicide-data.csv") %>% 
  mutate(city_state = str_c("city", "state", sep = "_"),
         victim_age = as.numeric(victim_age),
         resolution = case_when(
           disposition == "Closed without arrest" ~0,
           disposition == "Open/No arrest"        ~0,
           disposition == "Closed by arrest"      ~1)
    ) %>% 
  filter(
    victim_race %in% c("White", "Black"),
    city_state != "Tulsa_AL") %>% 
  select(city_state, resolution, victim_age, victim_race, victim_sex)
  
```

Start with once city.

```{r}
baltimore = homicide %>% 
  filter(city_state == "Baltimore_MD")

glm(resolution ~ victim_age + victim_race + victim_sex,
    data = baltimore,
    family = binomial()) %>% 
  broom::tidy() %>% 
  mutate(
    OR = exp(estimate - 1.96 * std.error)
  )

```

